---
services:
  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7473:7473
      - 7687:7687
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=none
    volumes:
      - data:/data
      - logs:/logs

  python-app:
    build:
      context: ../..
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./:/source
    environment:
      - NEO4J_URI=neo4j://neo4j:7687
    depends_on:
     - neo4j
volumes:
  data:
  logs: